### PR TITLE
Fixed syntax error in #53 

### PR DESCRIPTION
**Pull request by joeyfigaro**
#53

### CODE REVIEW

**Comment by BeckyWu220** [comment]
Hi @joeyfigaro Thanks for contributing to the library. Could you please update the PR by removing the `package.lock` file and the `.editorconfig` file? Thanks!

**Comment by BeckyWu220** [comment]
Hi! @joeyfigaro Sorry for responding late to your PR. As you might had noticed, we had some new PRs merged. One of the PR had provided a typescript implementation, and this issue had been fixed in the same PR. You should not encounter this issue again in the next release (v1.3.x). Please feel free to test again in the new version that would be released soon.

**Comment by joeyfigaro** [comment]
@BeckyWu220 no worries! is this good to close, then?

**Comment by BeckyWu220** [comment]
Hi @joeyfigaro Yes. I will go ahead and close the PR. Thanks for your contribution.

**Pull request closed without merging**
