### PR TITLE
typescript implementation

### LINKED ISSUE #28: componentWillReceiveProps deprecation
Screen Shot 2019-12-05 at 11 44 37 PM

### PR DESCRIPTION
**Pull request by mikhailshvets**
- added TypeScript implementation
- fixed #28

### CODE REVIEW

**Comment by BeckyWu220** [comment]
Hi @mikhailshvets Thank you very much for the PR. It is a great improvement to this library. We had reviewed your PR, and found in a new folder, `./lib` committed. 
I believe the folder includes all the compiled code generated by `npm run build`.  If my assumption is correct, it is not necessary to be committed because it would cause a great amount of git diff in the future. 
Please add the folder to .gitignore file, and untrack these `*.js` and `*.js.map`files. We are working on a automation release Github action, we can run the `build` script before releasing to npm. 
If you have any questions or concerns, please let us know. Thanks a lot for your contribution!

**Comment by mikhailshvets** [comment]
Hi @BeckyWu220 Could you review the changes and accept the PR if everything is ok now?

**Comment by BeckyWu220** [comment]
Hi, @mikhailshvets Thanks for making the change rapidly. To merge this PR without back-and-forth change, we had created a new PR based on this PR.  We had listed the 3 things we changed upon your awesome work, please feel free to check them out, and let us know if you have any questions or concerns. 

- There were a few PRs got merged before this PR, we had to do a git rebase to keep a clean git history. 
- While testing in the `example` folder, we found it caused failure to include the `metro.config.js` file. Since we are not really using the metro for bundling, we thought it's fine to skip it.
- We had refined the npm package auto-release GitHub action with your `npm run build` script.

We are doing the final testing, and are very close to release a new build generated by your typescript implementation. Since the new PR had been merged, we will close this PR next week. 
We'd like to thank you again for your time and contribution. As we treat this typescript integration as a great improvement to our library, we'd like to add your name into our external contributors list upon your approval. Thank you!

**Comment by mikhailshvets** [comment]
Hi, @BeckyWu220 Thanks for your feedback. I'd like to be an external contributor and improve the library in the future

**Comment by BeckyWu220** [comment]
Great! Thanks for confirmation with us. @mikhailshvets We had add you as external contributors in the README.md file. We will close this PR now.

**Pull request closed without merging**
